<?php

class PxlImageCarousel_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_image_carousel';
    protected $title = 'Case Image Carousel';
    protected $icon = 'eicon-media-carousel';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"items","label":"Partner","type":"repeater","controls":[{"name":"image","label":"Image","type":"media"}]}]},{"name":"section_settings_carousel","label":"Settings","tab":"settings","controls":[{"name":"col_xs","label":"Columns XS Devices","type":"select","default":"1","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"col_sm","label":"Columns SM Devices","type":"select","default":"2","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"col_md","label":"Columns MD Devices","type":"select","default":"3","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"col_lg","label":"Columns LG Devices","type":"select","default":"3","options":{"1":"1","2":"2","3":"3","4":"4","6":"6"}},{"name":"col_xl","label":"Columns XL Devices","type":"select","default":"3","options":{"1":"1","2":"2","3":"3","4":"4","5":"5","6":"6"}},{"name":"col_xxl","label":"Columns XXL Devices","type":"select","default":"3","options":{"1":"1","2":"2","3":"3","4":"4","5":"5","6":"6"}},{"name":"slides_to_scroll","label":"Slides to scroll","type":"select","default":"1","options":{"1":"1","2":"2","3":"3","4":"4","5":"5","6":"6"}},{"name":"arrows","label":"Show Arrows","type":"switcher","default":false},{"name":"arrow_version","label":"Arrows Style","type":"select","options":{"style-light":"Light","style-dark":"Dark"},"default":"style-light"},{"name":"arrows_label","label":"Arrows Label","type":"text","condition":{"arrows":"true"}},{"name":"pagination","label":"Show Pagination","type":"switcher","default":false},{"name":"pagination_type","label":"Pagination Type","type":"select","default":"bullets","options":{"bullets":"Bullets","fraction":"Fraction"},"condition":{"pagination":"true"}},{"name":"pause_on_hover","label":"Pause on Hover","type":"switcher","default":false},{"name":"autoplay","label":"Autoplay","type":"switcher","default":false},{"name":"autoplay_speed","label":"Autoplay Speed","type":"number","default":5000,"condition":{"autoplay":"true"}},{"name":"infinite","label":"Infinite Loop","type":"switcher","default":false},{"name":"speed","label":"Animation Speed","type":"number","default":500}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'swiper','pxl-swiper' );
}