<?php

class PxlPostAcccordion_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_post_acccordion';
    protected $title = 'Case Post Acccordion';
    protected $icon = 'eicon-posts-carousel';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"post_type","label":"Select Post Type","type":"select","multiple":true,"options":{"portfolio":"Portfolio"},"default":"post"},{"name":"layout_portfolio","label":"Select Template of Portfolio","type":"layoutcontrol","default":"portfolio-1","options":{"portfolio-1":{"label":"Layout 1","image":"http:\/\/localhost\/bravis-team\/zurick\/wp-content\/themes\/zurick\/elements\/widgets\/img-layout\/pxl_post_carousel\/portfolio-layout1.jpg"}},"prefix_class":"post-layout-","condition":{"post_type":["portfolio"]}}]},{"name":"section_source","label":"Source","tab":"settings","controls":[{"name":"select_post_by","label":"Select posts by","type":"select","multiple":true,"options":{"term_selected":"Terms selected","post_selected":"Posts selected "},"default":"term_selected"},{"name":"source_portfolio","label":"Select Term of Portfolio","type":"select2","multiple":true,"options":{"creative|portfolio-category":"Creative","invest-reporting|portfolio-category":"Invest Reporting","marketing|portfolio-category":"Marketing"},"condition":{"post_type":["portfolio"],"select_post_by":"term_selected"}},{"name":"source_portfolio_post_ids","label":"Select posts","type":"select2","multiple":true,"options":{"1758":"Creative Product Idea  for Nvana Inc.","1771":"Creative Product Idea  for Nvana Inc.","1774":"Investment Reporting For Marico","1776":"Investment Reporting For Marico a","1778":"Creative Product Idea  for Nvana Inc.","1780":"Creative Product Idea  for Nvana Inc.","1782":"Investment Reporting For Marico","1785":"Digital Marketing For Marico","2446":"Highlighting Key Projects in My Portfolio","5632":"Digital Marketing Campaign For Arnold Corporation","5638":"Financial Research For Axis Technology","5640":"Product Launch event for Procter and Gamble","5642":"New Product Idea Development for Nvana Inc."},"condition":{"post_type":["portfolio"],"select_post_by":"post_selected"}},{"name":"orderby","label":"Order By","type":"select","default":"date","options":{"date":"Date","ID":"ID","author":"Author","title":"Title","rand":"Random"}},{"name":"order","label":"Sort Order","type":"select","default":"desc","options":{"desc":"Descending","asc":"Ascending"}},{"name":"limit","label":"Total items","type":"number","default":"6"}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'swiper','pxl-swiper' );
}