<?php

class PxlButtonAnchor_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_button_anchor';
    protected $title = 'BR Button Anchor';
    protected $icon = 'eicon-anchor';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"section_content","label":"Content","tab":"content","controls":[{"name":"content_template","label":"Select Template","type":"select","options":{"0":"None","5674":"Panel Content Light","16715":"Panel Search Form Light","19725":"Panel Content Dark","20633":"Panel Search Form Dark"},"default":"df","description":"Add new tab template: \"<a href=\"http:\/\/leax.local\/wp-admin\/edit.php?post_type=pxl-template\" target=\"_blank\">Click Here<\/a>\""},{"name":"pxl_icon","label":"Icon","type":"icons","fa4compatibility":"icon"}]},{"name":"section_style","label":"Style","tab":"style","controls":[{"name":"normal","label":"NORMAL","type":"heading","sperator":"after"},{"name":"style","label":"Style","type":"select","default":"","options":{"":"Default","pxl-btn-search1":"Button Search - Border"}},{"name":"color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .pxl-button-anchor .pxl-item--button":"color: {{VALUE}}","{{WRAPPER}} .pxl-button-anchor .pxl-item--button svg circle":"fill: {{VALUE}}"}},{"name":"border","label":"Border","type":"border","control_type":"group","selector":"{{WRAPPER}} .pxl-button-anchor .pxl-item--button:after"},{"name":"font_size","label":"Size","type":"slider","control_type":"responsive","size_units":["px"],"selectors":{"{{WRAPPER}} .pxl-button-anchor .pxl-item--button":"font-size: {{SIZE}}{{UNIT}};"}},{"name":"height","label":"Height","type":"slider","control_type":"responsive","size_units":["px"],"range":{"px":{"min":0,"max":200}},"selectors":{"{{WRAPPER}} .pxl-button-anchor .pxl-item--button":"height: {{SIZE}}{{UNIT}};"}},{"name":"divider","type":"divider"},{"name":"hover","label":"HOVER","type":"heading","sperator":"after"},{"name":"border_color_hover","label":"Border Color","type":"color","selectors":{"{{WRAPPER}} .pxl-button-anchor .pxl-item--button:before":"border-color: {{VALUE}}"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}